repos:
  - repo: local
    hooks:
      - id: gfmd
        name: gfm-diagrams
        description: "GFM Diagrams"
        entry: pipenv run python -m gfmd
        language: system
        require_serial: true
        types: [file]
        files: ".*\\.md"

